name = "dev-encoding-toolkit"
type = "javascript"
account_id = ""
workers_dev = false
route = ""
zone_id = ""

# Cloudflare Pages settings
pages_build_output_dir = "out"

[env.production]
name = "dev-encoding-toolkit-prod"
route = "yourdomain.com/*"
zone_id = ""
